import json

urls = """
https://www.shwapno.com/aci
https://www.shwapno.com/aci-pure-chilli-morich-powder-200gm
https://www.shwapno.com/aci-pure-coriander-dhonia-powder-200gm
https://www.shwapno.com/aci-pure-cumin-jeera-powder-200gm
https://www.shwapno.com/aci-pure-foods
https://www.shwapno.com/aci-pure-shahi-biryani-masala-40gm-2
https://www.shwapno.com/aci-pure-turmeric-holud-powder-200gm
https://www.shwapno.com/air-fresheners
https://www.shwapno.com/ama-3in1-brazilian-coffee-15g-br
https://www.shwapno.com/ama-3in1-coffee-10-x-15g
https://www.shwapno.com/angelic-airfreshener-sparkling-orange-300ml
https://www.shwapno.com/baby-accessories
https://www.shwapno.com/baby-bath-and-skincare
https://www.shwapno.com/baby-food
https://www.shwapno.com/baby-food-and-care
https://www.shwapno.com/baby-oral-care
https://www.shwapno.com/baby-wipes
https://www.shwapno.com/baking-ingredients
https://www.shwapno.com/baking-needs
https://www.shwapno.com/bashundhara-paper-towel-white-250pcs-poly
https://www.shwapno.com/bashundhara-power-wash-detergent-1kg
https://www.shwapno.com/bashundhara-power-wash-detergent-lemon-1kg
https://www.shwapno.com/bath-and-body
https://www.shwapno.com/batteries
https://www.shwapno.com/beauty-and-health
https://www.shwapno.com/bedding
https://www.shwapno.com/bed-room-essentials
https://www.shwapno.com/beef
https://www.shwapno.com/belgiam-coffe-latte-chocolate-200gm
https://www.shwapno.com/belgiam-hearts-chocolate-200gm
https://www.shwapno.com/belgian-hearts-chocolate-65g
https://www.shwapno.com/beverages
https://www.shwapno.com/biscuits
https://www.shwapno.com/Biscuits-Others
https://www.shwapno.com/bisk-club-sugar-free-cracker-biscuit-20020gm
https://www.shwapno.com/Black-Tea-2
https://www.shwapno.com/blanket-and-comforter
https://www.shwapno.com/bombay-sweets-chanachur-50050gm
https://www.shwapno.com/brands
https://www.shwapno.com/bread-pit-soft-brown-w-meal-bread-300gm
https://www.shwapno.com/bread-pit-soft-white-milk-bread-300gm
https://www.shwapno.com/bread-pit-sugar-free-bread-400gm
https://www.shwapno.com/bread-pit-super-s-multigrain-bread-300gm
https://www.shwapno.com/bread-pit-white-sandwich-bread-300gm
https://www.shwapno.com/breads
https://www.shwapno.com/breakfast
https://www.shwapno.com/butter
https://www.shwapno.com/buy-save-more-2
https://www.shwapno.com/cadbury-dairy-milk-silk-fruit-and-nut-605gm
https://www.shwapno.com/cakes
https://www.shwapno.com/candy-chocolate
https://www.shwapno.com/Canned-Fish
https://www.shwapno.com/canned-food
https://www.shwapno.com/Canned-Fruits
https://www.shwapno.com/Canned-Meat-2
https://www.shwapno.com/Canned-Vegetables
https://www.shwapno.com/cat-food
https://www.shwapno.com/cereals
https://www.shwapno.com/Cheese
https://www.shwapno.com/cherien-pure-cotton-buds-100pcs-2
https://www.shwapno.com/chicken
https://www.shwapno.com/chips-and-pretzels
https://www.shwapno.com/Chopstick-Ramen-Hot-Chicken-Noodles-160g
https://www.shwapno.com/coffee
https://www.shwapno.com/Coffee-Mate
https://www.shwapno.com/Coffee-Others
https://www.shwapno.com/colgate-active-salt-toothpaste-200gm-2
https://www.shwapno.com/colgate-max-fresh-red-geltooth-paste-150gm-2
https://www.shwapno.com/colours
https://www.shwapno.com/colours-and-flavors
https://www.shwapno.com/condensed-milk-and-cream
https://www.shwapno.com/Conditioners
https://www.shwapno.com/ContactUs-2
https://www.shwapno.com/cooking
https://www.shwapno.com/cooking-sauce
https://www.shwapno.com/cookware
https://www.shwapno.com/cosmetics
https://www.shwapno.com/cream-and-lotion
https://www.shwapno.com/Cream-Sandwich-Biscuits
https://www.shwapno.com/crockeries
https://www.shwapno.com/cucumber-shosha-6
https://www.shwapno.com/cyprina-apple-juice-1-ltr-slim
https://www.shwapno.com/daal-or-lentil
https://www.shwapno.com/dairy
https://www.shwapno.com/davidoff-café-fine-aroma-100gm
https://www.shwapno.com/davidoff-café-rich-aroma-100gm-jar
https://www.shwapno.com/davidoff-espresso-coffee-100gm
https://www.shwapno.com/d-care-dish-washing-liquid-250ml-buy2-get-1-free
https://www.shwapno.com/deals
https://www.shwapno.com/deals-on-unilever
https://www.shwapno.com/dekko-egg-noodles-15020gm-buy3-get1-free
https://www.shwapno.com/deodorant
https://www.shwapno.com/Diabetic-Milk
https://www.shwapno.com/diabetic-sugar
https://www.shwapno.com/dipping-sauce
https://www.shwapno.com/dips-and-spreads
https://www.shwapno.com/dish-cleaner
https://www.shwapno.com/domex-ocean-fresh-toilet-cleaner-750ml
https://www.shwapno.com/dried-fruits
https://www.shwapno.com/drinking-water
https://www.shwapno.com/Dry-Cake
https://www.shwapno.com/dry-fruits
https://www.shwapno.com/dry-vegetables
https://www.shwapno.com/egg-loose
https://www.shwapno.com/eggs
https://www.shwapno.com/energy-and-malted-drinks
https://www.shwapno.com/Energy-Biscuit
https://www.shwapno.com/Fan
https://www.shwapno.com/fashion-and-lifestyle
https://www.shwapno.com/feminine-care
https://www.shwapno.com/ferrero-rocher-moments-92-8gm-india
https://www.shwapno.com/finis-finpic-toilet-cleaner-750ml-buy-1-get-1-free
https://www.shwapno.com/first-aid-and-antiseptics
https://www.shwapno.com/fish
https://www.shwapno.com/flask-pots-and-bottles
https://www.shwapno.com/flavored-oil
https://www.shwapno.com/Flavored-Tea
https://www.shwapno.com/floor-glass-and-wood-cleaners
https://www.shwapno.com/flours
https://www.shwapno.com/food
https://www.shwapno.com/French-Fries
https://www.shwapno.com/fresh-chilli-powder-200gm-2
https://www.shwapno.com/fresh-fruits
https://www.shwapno.com/fresh-ifcmp-milk-powder-500gm
https://www.shwapno.com/fresh-vegetables
https://www.shwapno.com/fresh-water-fish
https://www.shwapno.com/Frozen
https://www.shwapno.com/Frozen-Snacks-Others
https://www.shwapno.com/fruits-and-vegetables
https://www.shwapno.com/Full-Cream-Milk
https://www.shwapno.com/Gadget
https://www.shwapno.com/ghee
https://www.shwapno.com/ginnou-chocolate-88gm-heart-box
https://www.shwapno.com/ginnou-chocolate-box-205-30gm
https://www.shwapno.com/gorur-mangsho-alu-mix-small
https://www.shwapno.com/great-savings-3
https://www.shwapno.com/green-banana-kacha-kola-pcs
https://www.shwapno.com/green-papaya-6
https://www.shwapno.com/Green-Tea-2
https://www.shwapno.com/hair-care
https://www.shwapno.com/handwash-and-handrub
https://www.shwapno.com/harpoon-liquid-toilet-cleaner-500ml-buy-1-get-1-free
https://www.shwapno.com/health-care
https://www.shwapno.com/helpline
https://www.shwapno.com/herbal-and-digestive-aids
https://www.shwapno.com/home-and-kitchen
https://www.shwapno.com/Home-Appliance-2
https://www.shwapno.com/home-cleaning
https://www.shwapno.com/honey
https://www.shwapno.com/ice-cream
https://www.shwapno.com/ifad-bd-kaju-175gm-buy3-get120gm-milk-biscuit-free
https://www.shwapno.com/impel-comforter-double-2023
https://www.shwapno.com/Instant-Coffee
https://www.shwapno.com/Iron
https://www.shwapno.com/jam-and-jelly
https://www.shwapno.com/johnsons-baby-milk-cream-50-gm-tube-indian
https://www.shwapno.com/johnsons-moisture-soft-cream-200ml-2
https://www.shwapno.com/juice
https://www.shwapno.com/karnaval-almond-cream-chocolate-125-gm-turkey
https://www.shwapno.com/karnaval-coconut-cream-chocolate-125-gm-turkey
https://www.shwapno.com/karnaval-strawberry-a-h-c-c-chocolate-125-gm-turkey
https://www.shwapno.com/karnaval-strawberry-carnival-chocolate-125-gm-turkey
https://www.shwapno.com/kazi-and-kazi-family-pack-tea-400g
https://www.shwapno.com/kazi-and-kazi-green-tea-bag-60gm
https://www.shwapno.com/kitchen-accessories
https://www.shwapno.com/kitchen-appliances
https://www.shwapno.com/kodomo-baby-shampoo-and-original-200ml
https://www.shwapno.com/kodomo-baby-shampoogentle-soft200ml
https://www.shwapno.com/krystalklean-liquid-dishwash-500mlb2g1f
https://www.shwapno.com/kurtis-tunics-and-tops
https://www.shwapno.com/Laban
https://www.shwapno.com/Lacchi
https://www.shwapno.com/laundry
https://www.shwapno.com/lemon-long-lomba-lebu-pcs
https://www.shwapno.com/lights-and-electrical
https://www.shwapno.com/liquid-and-uht-milk
https://www.shwapno.com/living-items
https://www.shwapno.com/local-snacks
https://www.shwapno.com/loose-daal
https://www.shwapno.com/loose-rice
https://www.shwapno.com/Low-Fat-Milk
https://www.shwapno.com/Low-Fat-Milk-2
https://www.shwapno.com/lungi
https://www.shwapno.com/Macaroni
https://www.shwapno.com/maccoffee-gold-freeze-dried-coffee-100gm
https://www.shwapno.com/marico
https://www.shwapno.com/marks-milk-based-diabetic-diet-tin-400gm
https://www.shwapno.com/mayonnaise
https://www.shwapno.com/meat
https://www.shwapno.com/meat-and-fish
https://www.shwapno.com/Medical-Devices
https://www.shwapno.com/meril-baby-brushing-training-kit-45gm
https://www.shwapno.com/meril-baby-lotion-100-ml
https://www.shwapno.com/mgi
https://www.shwapno.com/Milk-Biscuits
https://www.shwapno.com/Milk-Others
https://www.shwapno.com/mishti-kumra-kg
https://www.shwapno.com/Mixed-Spice
https://www.shwapno.com/mr-noodles-korean-super-spicy-496gm
https://www.shwapno.com/mr-white-detergent-powder-500gm-buy-3-get-1-free
https://www.shwapno.com/mustard-oil
https://www.shwapno.com/mutton
https://www.shwapno.com/nestle
https://www.shwapno.com/nior-dreamy-glow-brightening-cream-50ml-2
https://www.shwapno.com/nivea-men-extra-bright-10-x-effect-foam-100-gm-2
https://www.shwapno.com/Non-Fat-Milk
https://www.shwapno.com/Noodles
https://www.shwapno.com/Nuggets
https://www.shwapno.com/Office-Address
https://www.shwapno.com/office-products
https://www.shwapno.com/oil
https://www.shwapno.com/olive-oil
https://www.shwapno.com/oral-care
https://www.shwapno.com/other-birds
https://www.shwapno.com/our-outlets
https://www.shwapno.com/packed-daal
https://www.shwapno.com/packed-rice
https://www.shwapno.com/Paratha
https://www.shwapno.com/Pasta
https://www.shwapno.com/personal-care
https://www.shwapno.com/personal-grooming
https://www.shwapno.com/pest-control
https://www.shwapno.com/pet-care
https://www.shwapno.com/pickle-and-condiments
https://www.shwapno.com/pillow-and-cushion
https://www.shwapno.com/popcorn-and-nuts
https://www.shwapno.com/powder-milk
https://www.shwapno.com/Powder-Milk-Others
https://www.shwapno.com/pran-cumin-seed-powder-25050gm-jar-2
https://www.shwapno.com/pran-diabetic-orange-jelly-500gm-2
https://www.shwapno.com/pran-full-cream-milk-powder-500gm
https://www.shwapno.com/pran-mr-noodles-easy-magic-masala-496gm
https://www.shwapno.com/pureit-classic-germ-kill-kit-1500l
https://www.shwapno.com/pusti-soyabean-oil-5liter
https://www.shwapno.com/quaker-oats-500gm-jar
https://www.shwapno.com/radhuni-chicken-tandoori-masala-50gm-2
https://www.shwapno.com/radhuni-chilli-morich-powder-500gm
https://www.shwapno.com/radhuni-coriander-dhonia-powder-200gm
https://www.shwapno.com/radhuni-cumin-jeera-powder-50gm
https://www.shwapno.com/radhuni-cumin-jeera-powder-100gm
https://www.shwapno.com/radhuni-haleem-mix-200gm
https://www.shwapno.com/radhuni-kachchi-biryani-masala-40gm-2
https://www.shwapno.com/radhuni-turmeric-holud-powder-100gm
https://www.shwapno.com/reckitt
https://www.shwapno.com/red-amaranth-spinach-lal-shak-per-bunch
https://www.shwapno.com/red-cow-instant-full-cream-milk-powder-500gm
https://www.shwapno.com/Regular-Spice
https://www.shwapno.com/rice
https://www.shwapno.com/rice-bran-oil
https://www.shwapno.com/rok-glass-cleaner-350100ml-spray
https://www.shwapno.com/rok-liquid-dishwash-750ml-buy1-get-250ml-refill-free
https://www.shwapno.com/ruchi-bbq-chanachur-500gm
https://www.shwapno.com/ruchi-bbq-chanachur-35050gm
https://www.shwapno.com/rupchanda-soyabean-oil-5liter
https://www.shwapno.com/s203121-electric-kettle-1-8l-2023
https://www.shwapno.com/s203121-noah-e-blender-888-2024
https://www.shwapno.com/salt
https://www.shwapno.com/salt-and-sugar
https://www.shwapno.com/Salted
https://www.shwapno.com/Samosa
https://www.shwapno.com/sauces
https://www.shwapno.com/sauces-and-pickles
https://www.shwapno.com/Sausage
https://www.shwapno.com/savlon-twinkle-baby-diaper-xxl-24pcs-2
https://www.shwapno.com/sea-fish
https://www.shwapno.com/sensodyne-expert-buy2-get1-free
https://www.shwapno.com/sensodyne-fresh-gel-toothpaste-150gm-brush-free
https://www.shwapno.com/sensodyne-fresh-mint-toothpaste-150gm-brush-free
https://www.shwapno.com/Shampoo
https://www.shwapno.com/shaving-and-facial-care
https://www.shwapno.com/shemai-and-suji
https://www.shwapno.com/shinex-glass-cleaner-spray-350ml
https://www.shwapno.com/ShippingInfo
https://www.shwapno.com/shwapno
https://www.shwapno.com/shwapno-kaju-badam-cashew-nuts-100gm-2
https://www.shwapno.com/shwapno-kath-badam-almond-50gm-2
https://www.shwapno.com/shwapno-kismis-raisins-200gm-2
https://www.shwapno.com/Singara
https://www.shwapno.com/sis-low-gi-sugar-350-gm-sin
https://www.shwapno.com/skincare
https://www.shwapno.com/skirts-and-palazzos
https://www.shwapno.com/snacks
https://www.shwapno.com/snickers-chocolate-253gm-buy3-get1-free
https://www.shwapno.com/soft-drinks
https://www.shwapno.com/soup
https://www.shwapno.com/soybean-oil
https://www.shwapno.com/specialdiscounts
https://www.shwapno.com/spices
https://www.shwapno.com/spoons-forks-and-others
https://www.shwapno.com/square-toiletries
https://www.shwapno.com/sugar
https://www.shwapno.com/Sugar-Free-Biscuits
https://www.shwapno.com/sunflower-oil
https://www.shwapno.com/surf-excel-1-kg
https://www.shwapno.com/surf-excel-matic-liquid-top-load-500ml
https://www.shwapno.com/syrups-and-powder-drinks
https://www.shwapno.com/tac
https://www.shwapno.com/talcum-powder
https://www.shwapno.com/tayas-orient-hazelnut-250-gm
https://www.shwapno.com/tayas-orient-strawberry-250gm
https://www.shwapno.com/tea
https://www.shwapno.com/Tea-Others
https://www.shwapno.com/tissue-and-wipes
https://www.shwapno.com/Toast-Biscuit
https://www.shwapno.com/toilet-cleaners
https://www.shwapno.com/tools-and-hardware
https://www.shwapno.com/towels
https://www.shwapno.com/toys-and-sports
https://www.shwapno.com/toys-items
https://www.shwapno.com/trash-supplies
https://www.shwapno.com/unilever
https://www.shwapno.com/vaseline-g-glow-lotion-400ml-kajal-free
https://www.shwapno.com/vaseline-intccocoaglow-lotion-200ml-za
https://www.shwapno.com/vim-dishwash-liquid-1ltr-
https://www.shwapno.com/vim-dishwash-liquid-refill-pack-250ml
https://www.shwapno.com/water-spinach-kolmi-shak-per-bunch
https://www.shwapno.com/wheel-2in1-cleanandfresh-detergent-2kg
https://www.shwapno.com/wheel-laundry-soap-125gm
https://www.shwapno.com/Wholespice
https://www.shwapno.com/Winter-Care
https://www.shwapno.com/womens-care-collection
https://www.shwapno.com/writing-and-drawing
https://www.shwapno.com/Yogurt
https://www.shwapno.com/zerocal-sachet-25pcs-2
https://www.shwapno.com/zerocal-tablet-100pcs-2
"""

categories = []
for line in urls.splitlines():
    url = line.strip()
    if url:
        name = url.split('/')[-1].replace('-', ' ').title()
        categories.append({
            "name": name,
            "url": url,
            "enabled": True
        })

with open('categories.json', 'w') as f:
    json.dump(categories, f, indent=2)

print(f"Generated {len(categories)} categories.")
